### ISSUE TITLE
https://github.com/mo4islona/node-blockly

### ISSUE THREAD

**Issue by Alexejhero** [YannCaron/node-blockly#2]
What's the difference between this repo and https://github.com/mo4islona/node-blockly?

**Comment by YannCaron** [comment]
Yes ! I forked the original repository because sub modules was not complete.
see : [first commit](https://github.com/YannCaron/node-blockly/commit/87f1504ebbbafe2c5e316cc0cff3acb58ce7ff86)

A also change some building scripts.
